### ISSUE TITLE
Unable to connect to Kernel

### ISSUE THREAD

**Issue by lostandbored** [moezali1/MMA865#10]
**General Problem**

Hello Moez, Rishi, and classmates,

My technical issue is that my MMA kernel is not connecting. When I try to install/upgrade packages the errors Jupyter notebook shows (error codes pasted below), I get another error from my command prompt (also pasted below). 

I tried removing the 260 Character Path Limit by changing LongPathsEnabled to 1 in hopes of fixing the command prompt error, but that did not work. 

Any suggestions?  Thanks in advance!

**Command Prompt Error** (e.g. after trying to install "pip install zmq" or "pip install --upgrade pip"):

WARNING: Error parsing requirements for mistune: [Errno 2] No such file or directory: 'c:\\users\\surab\\anaconda3\\envs\\mma\\lib\\site-packages\\mistune-0.8.4.dist-info\\METADATA'

**Jupyter Notebook Error:**

[I 15:52:42.082 NotebookApp] JupyterLab extension loaded from C:\Users\surab\anaconda3\lib\site-packages\jupyterlab
[I 15:52:42.082 NotebookApp] JupyterLab application directory is C:\Users\surab\anaconda3\share\jupyter\lab
[I 15:52:42.102 NotebookApp] Serving notebooks from local directory: C:\Users\surab
[I 15:52:42.102 NotebookApp] The Jupyter Notebook is running at:
[I 15:52:42.102 NotebookApp] http://localhost:8888/?token=461a70c5aecf2f7fbec1127377404e56e2e76a71915ae312
[I 15:52:42.102 NotebookApp]  or http://127.0.0.1:8888/?token=461a70c5aecf2f7fbec1127377404e56e2e76a71915ae312
[I 15:52:42.103 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 15:52:42.163 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/surab/AppData/Roaming/jupyter/runtime/nbserver-27780-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=461a70c5aecf2f7fbec1127377404e56e2e76a71915ae312
     or http://127.0.0.1:8888/?token=461a70c5aecf2f7fbec1127377404e56e2e76a71915ae312
[I 15:53:13.689 NotebookApp] Creating new notebook in
[I 15:53:15.467 NotebookApp] Kernel started: 67cd0462-9f80-42e5-9d5c-855870adbc3f
Traceback (most recent call last):
  File "C:\Users\surab\anaconda3\envs\MMA\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\surab\anaconda3\envs\MMA\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\ipykernel\connect.py", line 11, in <module>
    import jupyter_client
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\jupyter_client\connect.py", line 21, in <module>
    import zmq
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\zmq\__init__.py", line 103, in <module>
    from zmq import backend
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\zmq\backend\__init__.py", line 32, in <module>
    raise original_error from None
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\zmq\backend\select.py", line 32, in select_backend
    mod = import_module(name)
  File "C:\Users\surab\anaconda3\envs\MMA\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (
ImportError: DLL load failed while importing error: The specified module could not be found.
[I 15:53:18.448 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
  File "C:\Users\surab\anaconda3\envs\MMA\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\surab\anaconda3\envs\MMA\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\ipykernel\connect.py", line 11, in <module>
    import jupyter_client
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\jupyter_client\connect.py", line 21, in <module>
    import zmq
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\zmq\__init__.py", line 103, in <module>
    from zmq import backend
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\zmq\backend\__init__.py", line 32, in <module>
    raise original_error from None
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\zmq\backend\select.py", line 32, in select_backend
    mod = import_module(name)
  File "C:\Users\surab\anaconda3\envs\MMA\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (
ImportError: DLL load failed while importing error: The specified module could not be found.
[I 15:53:21.460 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
Traceback (most recent call last):
  File "C:\Users\surab\anaconda3\envs\MMA\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\surab\anaconda3\envs\MMA\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\ipykernel\connect.py", line 11, in <module>
    import jupyter_client
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\jupyter_client\connect.py", line 21, in <module>
    import zmq
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\zmq\__init__.py", line 103, in <module>
    from zmq import backend
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\zmq\backend\__init__.py", line 32, in <module>
    raise original_error from None
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\zmq\backend\select.py", line 32, in select_backend
    mod = import_module(name)
  File "C:\Users\surab\anaconda3\envs\MMA\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (
ImportError: DLL load failed while importing error: The specified module could not be found.
[I 15:53:24.459 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
Traceback (most recent call last):
  File "C:\Users\surab\anaconda3\envs\MMA\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\surab\anaconda3\envs\MMA\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\ipykernel\connect.py", line 11, in <module>
    import jupyter_client
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\jupyter_client\connect.py", line 21, in <module>
    import zmq
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\zmq\__init__.py", line 103, in <module>
    from zmq import backend
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\zmq\backend\__init__.py", line 32, in <module>
    raise original_error from None
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\zmq\backend\select.py", line 32, in select_backend
    mod = import_module(name)
  File "C:\Users\surab\anaconda3\envs\MMA\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (
ImportError: DLL load failed while importing error: The specified module could not be found.
[I 15:53:27.461 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
Traceback (most recent call last):
  File "C:\Users\surab\anaconda3\envs\MMA\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\surab\anaconda3\envs\MMA\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\ipykernel\connect.py", line 11, in <module>
    import jupyter_client
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\jupyter_client\connect.py", line 21, in <module>
    import zmq
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\zmq\__init__.py", line 103, in <module>
    from zmq import backend
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\zmq\backend\__init__.py", line 32, in <module>
    raise original_error from None
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\zmq\backend\select.py", line 32, in select_backend
    mod = import_module(name)
  File "C:\Users\surab\anaconda3\envs\MMA\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\surab\anaconda3\envs\MMA\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (
ImportError: DLL load failed while importing error: The specified module could not be found.
[W 15:53:30.475 NotebookApp] KernelRestarter: restart failed
[W 15:53:40.407 NotebookApp] Kernel 67cd0462-9f80-42e5-9d5c-855870adbc3f died, removing from map.

**Comment by Rjotsin** [comment]
Hi I think you emailed me, I had stated that you should be doing everything from anaconda prompt, including `conda activate mma` . When you do activate everything via anaconda, does it work?

**Comment by moezali1** [comment]
Hi @lostandbored 

Can you please confirm if the said issue has been resolved? If yes, can you please close this ticket?

Thanks

**Comment by lostandbored** [comment]
Thank you, the problem has been resolved!
